### PR TITLE
Added handling for mono

### PR DESCRIPTION
**Pull request by hartmark**
Added some conditionals to make mono compileable on Linux.

Keep up the good work :100:

### CODE REVIEW

**Comment by rajko-horvat** [comment]
Changes implemented

**Comment by hartmark** [comment]
Cool, l'll check it out after work

**Comment by hartmark** [comment]
Yes it's working using ~/Dos/Civ1
I get this screen now:
image

I guess that's where you are now in the implementation, keep up the good work.

**Comment by rajko-horvat** [comment]
No, the game loads completely. It's just that it can't find certain file(s). You can look into Log.txt file which is created at the assigned path '~/Dos/Civ1/Log.txt' and search for 'Opening file' phrase to see which file(s) it can't find. I guess the difference is lowercase/uppercase as the game is not aware of a distinction. This will later be fixed.
You can help me by compiling a list of file names (as they should be) for me to include in file list check.

Thanks :)

**Comment by rajko-horvat** [comment]
I had to poke with repository and restore to an earlier commit, so you'll have to pull repository again.
I have added resource file check, so if any resource file is missing you'll get the message. I also forced all file names to lowercase, because old code mixes lowercase and uppercase because DOS was ignorant in that way.

**Pull request closed without merging**
