### PR TITLE
feature: cross-platform UI

### PR DESCRIPTION
**Pull request by maximilien-noal**
### Description of Changes

Brings a cross-platform UI, thanks to AvaloniaUI.

Keeps the WinForms client as a comparison (for now).

Separates OpenCiv1 assembly from the UI.

### Rationale behind Changes

Enables more contributions from people who don"t use Windows.

Enables the game to run on Linux, Mac, while still running on Windows.

The structure also enable the reuse of the OpenCiv1.UI assembly for a Blazor or Avalonia WASM project, and iOS and Android projects.

### Suggested Testing Steps

image

Two things to fix in RedrawScreen: wrong colors and wrong coords.

Also the MessageBox that confirms the user exiting the app arrives too late (the app has already closed.

### CODE REVIEW

**Comment by maximilien-noal** [comment]
Update:

Two things to fix in RedrawScreen: wrong colors and wrong coords.

image

Also the MessageBox that confirms the user exiting the app arrives too late (the app has already closed)

**Comment by maximilien-noal** [comment]
image

The only thing left to fix seems to be the keyboard. I can't skip the intro...?

**Comment by siebenstreich** [comment]
> Enables the game to run on Linux, Mac, while still running on Windows.

A big thumbs-up for explicitly paying attention to Linux-compatibility!

**Comment by rajko-horvat** [comment]
> > Enables the game to run on Linux, Mac, while still running on Windows.
> 
> A big thumbs-up for explicitly paying attention to Linux-compatibility!

I'm currently testing it under Linux ;)

**Comment by richardpenman** [comment]
wow that is remarkable - running civ1 on Linux without an emulator!

**Pull request closed without merging**
